//! Shipped learned-model parameters. SEED VALUES — regenerated by `trainer emit`.
//! Do not edit by hand once trained; re-run the trainer instead.
use crate::learned::features::{feature_count, SCHEMA_VERSION};
use crate::learned::model::LinearModel;

/// The model embedded in the binary. Seed: positive weight on difficulty-y
/// features, identity standardization (means=0, stds=1) so seed behaves sanely.
pub fn shipped_model() -> LinearModel {
    let n = feature_count();
    let mut weights = vec![0.0_f64; n];
    // explicit feature indices (see features.rs order)
    weights[0] = 1.0; // length_contrib
    weights[1] = 1.0; // has_code
    weights[2] = 0.8; // has_math
    weights[3] = 0.5; // reasoning_hits
    weights[4] = 0.6; // multi_constraint
    weights[5] = 0.4; // structured_output
    weights[6] = 0.4; // explanation_request
    LinearModel {
        schema_version: SCHEMA_VERSION,
        weights,
        bias: -1.0,
        means: vec![0.0; n],
        stds: vec![1.0; n],
    }
}
