//! Shipped budget dimension heads. GENERATED by `trainer fit-budget` — do not edit by hand.
//! Placeholder (zero heads) until real 6-dim labels are fit; see PLAN-v3 Task 16.
use crate::budget::dims::{BUDGET_SCHEMA_VERSION, N_DIMS};
use crate::learned::features::{feature_count, SCHEMA_VERSION};
use crate::learned::model::LinearModel;

pub fn shipped_dim_models() -> Vec<LinearModel> {
    assert_eq!(SCHEMA_VERSION, 1, "weights/features schema mismatch");
    assert_eq!(BUDGET_SCHEMA_VERSION, 1, "budget schema mismatch");
    let n = feature_count();
    (0..N_DIMS)
        .map(|_| LinearModel {
            schema_version: SCHEMA_VERSION,
            weights: vec![0.0; n],
            bias: 0.0,
            means: vec![0.0; n],
            stds: vec![1.0; n],
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ships_six_well_formed_heads() {
        let models = shipped_dim_models();
        assert_eq!(models.len(), N_DIMS);
        for m in &models {
            assert_eq!(m.weights.len(), feature_count());
            assert_eq!(m.means.len(), feature_count());
            assert_eq!(m.stds.len(), feature_count());
        }
    }
}
