use route_llm_core::learned::model::LinearModel;

/// Render `weights.rs` source from a fitted model. `{:?}` on f64 is round-trippable.
pub fn weights_rs(m: &LinearModel) -> String {
    let fmt = |v: &[f64]| {
        v.iter()
            .map(|x| format!("{x:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "//! Shipped learned-model parameters. GENERATED by `trainer fit` — do not edit by hand.\n\
         use crate::learned::features::SCHEMA_VERSION;\n\
         use crate::learned::model::LinearModel;\n\n\
         pub fn shipped_model() -> LinearModel {{\n\
         \x20   assert_eq!(SCHEMA_VERSION, {schema}, \"weights/features schema mismatch\");\n\
         \x20   LinearModel {{\n\
         \x20       schema_version: {schema},\n\
         \x20       weights: vec![{w}],\n\
         \x20       bias: {b:?},\n\
         \x20       means: vec![{me}],\n\
         \x20       stds: vec![{st}],\n\
         \x20   }}\n\
         }}\n",
        schema = m.schema_version,
        w = fmt(&m.weights),
        b = m.bias,
        me = fmt(&m.means),
        st = fmt(&m.stds),
    )
}

pub fn write(m: &LinearModel, path: &str) -> Result<(), String> {
    std::fs::write(path, weights_rs(m)).map_err(|e| format!("write {path}: {e}"))
}

/// Render `crates/core/src/budget/weights.rs` from six fitted dimension heads.
pub fn budget_weights_rs(models: &[LinearModel]) -> String {
    let fmt = |v: &[f64]| {
        v.iter()
            .map(|x| format!("{x:?}"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let heads = models
        .iter()
        .map(|m| {
            format!(
                "        LinearModel {{\n\
                 \x20           schema_version: {schema},\n\
                 \x20           weights: vec![{w}],\n\
                 \x20           bias: {b:?},\n\
                 \x20           means: vec![{me}],\n\
                 \x20           stds: vec![{st}],\n\
                 \x20       }},",
                schema = m.schema_version,
                w = fmt(&m.weights),
                b = m.bias,
                me = fmt(&m.means),
                st = fmt(&m.stds),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "//! Shipped budget dimension heads. GENERATED by `trainer fit-budget` — do not edit by hand.\n\
         use crate::budget::dims::BUDGET_SCHEMA_VERSION;\n\
         use crate::learned::features::SCHEMA_VERSION;\n\
         use crate::learned::model::LinearModel;\n\n\
         pub fn shipped_dim_models() -> Vec<LinearModel> {{\n\
         \x20   assert_eq!(SCHEMA_VERSION, 1, \"weights/features schema mismatch\");\n\
         \x20   assert_eq!(BUDGET_SCHEMA_VERSION, 1, \"budget schema mismatch\");\n\
         \x20   vec![\n{heads}\n    ]\n\
         }}\n"
    )
}

pub fn write_budget(models: &[LinearModel], path: &str) -> Result<(), String> {
    std::fs::write(path, budget_weights_rs(models)).map_err(|e| format!("write {path}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use route_llm_core::learned::features::{feature_count, SCHEMA_VERSION};

    #[test]
    fn emitted_source_has_expected_shape() {
        let n = feature_count();
        let m = LinearModel {
            schema_version: SCHEMA_VERSION,
            weights: vec![0.5; n],
            bias: -1.25,
            means: vec![0.0; n],
            stds: vec![1.0; n],
        };
        let s = weights_rs(&m);
        assert!(s.contains("pub fn shipped_model()"));
        assert!(s.contains("bias: -1.25"));
        assert!(s.contains("schema_version: 1"));
    }

    #[test]
    fn budget_weights_source_has_six_heads() {
        let n = feature_count();
        let head = LinearModel {
            schema_version: SCHEMA_VERSION,
            weights: vec![0.25; n],
            bias: -0.5,
            means: vec![0.0; n],
            stds: vec![1.0; n],
        };
        let models = vec![head; 6];
        let s = budget_weights_rs(&models);
        assert!(s.contains("pub fn shipped_dim_models()"));
        assert_eq!(s.matches("LinearModel {").count(), 6);
        assert!(s.contains("bias: -0.5"));
    }
}
